### ISSUE TITLE
on shared hosting escapeshellarg() disabled cause security reason, on Spatie/laravel-medialibrary

### ISSUE THREAD

**Issue by vtscode** [LaravelDaily/Laravel-Event-Conference-Demo#1]
all the pictures and file media cant be read properly and when create or update new images it will return escapeshellarg() disabled and errror on shared hosting :

```
namespace Spatie\ImageOptimizer\Optimizers;

abstract class BaseOptimizer implements Optimizer
{
.......

public function getCommand(): string
    {
        $optionString = implode(' ', $this->options);
        return "\"{$this->binaryPath}{$this->binaryName}\" {$optionString}".escapeshellarg($this->imagePath);
    }
}
```
 on local it work fine, but on shared hosting it doesnt work on library for spatie for media

Please how to fix this issue. here my email: ventuscode@gmail.com
Thanks btw. :+1:

**Comment by PovilasKorop** [comment]
I see the only real fix for this is to change hosting to normal one which would support such things.

**Comment by vtscode** [comment]
> I see the only real fix for this is to change hosting to normal one which would support such things.

yes, it does, now im changing to new hosting, and that works.
