### ISSUE TITLE
I got this error when try to use the laravel conference project code

### ISSUE THREAD

**Issue by mafuz** [LaravelDaily/Laravel-Event-Conference-Demo#2]
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.2 but your PHP version (5.6.40) does not satisfy that requirement.        
  Problem 2
    - Installation request for doctrine/cache v1.8.0 -> satisfiable by doctrine/cache[v1.8.0].
    - doctrine/cache v1.8.0 requires php ~7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 3
    - Installation request for doctrine/dbal v2.9.2 -> satisfiable by doctrine/dbal[v2.9.2].
    - doctrine/dbal v2.9.2 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 4
    - Installation request for doctrine/event-manager v1.0.0 -> satisfiable by doctrine/event-manager[v1.0.0].
    - doctrine/event-manager v1.0.0 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 5
    - Installation request for doctrine/inflector v1.3.0 -> satisfiable by doctrine/inflector[v1.3.0].
    - doctrine/inflector v1.3.0 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 6
    - Installation request for doctrine/lexer 1.1.0 -> satisfiable by doctrine/lexer[1.1.0].
    - doctrine/lexer 1.1.0 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 7
    - Installation request for dragonmantank/cron-expression v2.3.0 -> satisfiable by dragonmantank/cron-expression[v2.3.0].
    - dragonmantank/cron-expression v2.3.0 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 8
    - Installation request for laravel/framework v6.0.4 -> satisfiable by laravel/framework[v6.0.4].
    - laravel/framework v6.0.4 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 9
    - Installation request for laravel/passport v7.4.1 -> satisfiable by laravel/passport[v7.4.1].
    - laravel/passport v7.4.1 requires php >=7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 10
    - Installation request for league/oauth2-server 7.4.0 -> satisfiable by league/oauth2-server[7.4.0].
    - league/oauth2-server 7.4.0 requires php >=7.0.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 11
    - Installation request for maennchen/zipstream-php 1.2.0 -> satisfiable by maennchen/zipstream-php[1.2.0].
    - maennchen/zipstream-php 1.2.0 requires php >= 7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 12
    - Installation request for monolog/monolog 2.0.0 -> satisfiable by monolog/monolog[2.0.0].
    - monolog/monolog 2.0.0 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 13
    - Installation request for myclabs/php-enum 1.7.2 -> satisfiable by myclabs/php-enum[1.7.2].
    - myclabs/php-enum 1.7.2 requires php >=7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 14
    - Installation request for nesbot/carbon 2.24.0 -> satisfiable by nesbot/carbon[2.24.0].
    - nesbot/carbon 2.24.0 requires php ^7.1.8 || ^8.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 15
    - Installation request for nikic/php-parser v4.2.4 -> satisfiable by nikic/php-parser[v4.2.4].
    - nikic/php-parser v4.2.4 requires php >=7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 16
    - Installation request for paragonie/random_compat v9.99.99 -> satisfiable by paragonie/random_compat[v9.99.99].
    - paragonie/random_compat v9.99.99 requires php ^7 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 17
    - Installation request for psr/http-factory 1.0.1 -> satisfiable by psr/http-factory[1.0.1].
    - psr/http-factory 1.0.1 requires php >=7.0.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 18
    - Installation request for spatie/image 1.7.4 -> satisfiable by spatie/image[1.7.4].
    - spatie/image 1.7.4 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 19
    - Installation request for spatie/image-optimizer 1.2.0 -> satisfiable by spatie/image-optimizer[1.2.0].
    - spatie/image-optimizer 1.2.0 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 20
    - Installation request for spatie/laravel-medialibrary 7.12.2 -> satisfiable by spatie/laravel-medialibrary[7.12.2].
    - spatie/laravel-medialibrary 7.12.2 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 21
    - Installation request for spatie/temporary-directory 1.2.1 -> satisfiable by spatie/temporary-directory[1.2.1].
    - spatie/temporary-directory 1.2.1 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 22
    - Installation request for swiftmailer/swiftmailer v6.2.1 -> satisfiable by swiftmailer/swiftmailer[v6.2.1].
    - swiftmailer/swiftmailer v6.2.1 requires php >=7.0.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 23
    - Installation request for symfony/console v4.3.4 -> satisfiable by symfony/console[v4.3.4].
    - symfony/console v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 24
    - Installation request for symfony/css-selector v4.3.4 -> satisfiable by symfony/css-selector[v4.3.4].
    - symfony/css-selector v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 25
    - Installation request for symfony/debug v4.3.4 -> satisfiable by symfony/debug[v4.3.4].
    - symfony/debug v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 26
    - Installation request for symfony/event-dispatcher v4.3.4 -> satisfiable by symfony/event-dispatcher[v4.3.4].
    - symfony/event-dispatcher v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 27
    - Installation request for symfony/event-dispatcher-contracts v1.1.5 -> satisfiable by symfony/event-dispatcher-contracts[v1.1.5].
    - symfony/event-dispatcher-contracts v1.1.5 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 28
    - Installation request for symfony/finder v4.3.4 -> satisfiable by symfony/finder[v4.3.4].
    - symfony/finder v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 29
    - Installation request for symfony/http-foundation v4.3.4 -> satisfiable by symfony/http-foundation[v4.3.4].
    - symfony/http-foundation v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 30
    - Installation request for symfony/http-kernel v4.3.4 -> satisfiable by symfony/http-kernel[v4.3.4].
    - symfony/http-kernel v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 31
    - Installation request for symfony/mime v4.3.4 -> satisfiable by symfony/mime[v4.3.4].
    - symfony/mime v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 32
    - Installation request for symfony/process v4.3.4 -> satisfiable by symfony/process[v4.3.4].
    - symfony/process v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 33
    - Installation request for symfony/psr-http-message-bridge v1.2.0 -> satisfiable by symfony/psr-http-message-bridge[v1.2.0].
    - symfony/psr-http-message-bridge v1.2.0 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 34
    - Installation request for symfony/routing v4.3.4 -> satisfiable by symfony/routing[v4.3.4].
    - symfony/routing v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 35
    - Installation request for symfony/service-contracts v1.1.6 -> satisfiable by symfony/service-contracts[v1.1.6].
    - symfony/service-contracts v1.1.6 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 36
    - Installation request for symfony/translation v4.3.4 -> satisfiable by symfony/translation[v4.3.4].
    - symfony/translation v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 37
    - Installation request for symfony/translation-contracts v1.1.6 -> satisfiable by symfony/translation-contracts[v1.1.6].
    - symfony/translation-contracts v1.1.6 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 38
    - Installation request for symfony/var-dumper v4.3.4 -> satisfiable by symfony/var-dumper[v4.3.4].
    - symfony/var-dumper v4.3.4 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 39
    - Installation request for yajra/laravel-datatables-oracle v9.6.0 -> satisfiable by yajra/laravel-datatables-oracle[v9.6.0].
    - yajra/laravel-datatables-oracle v9.6.0 requires php ^7.1.3 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 40
    - Installation request for zendframework/zend-diactoros 2.1.3 -> satisfiable by zendframework/zend-diactoros[2.1.3].
    - zendframework/zend-diactoros 2.1.3 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 41
    - Installation request for doctrine/instantiator 1.2.0 -> satisfiable by doctrine/instantiator[1.2.0].
    - doctrine/instantiator 1.2.0 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 42
    - Installation request for facade/flare-client-php 1.0.4 -> satisfiable by facade/flare-client-php[1.0.4].
    - facade/flare-client-php 1.0.4 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 43
    - Installation request for facade/ignition 1.8.2 -> satisfiable by facade/ignition[1.8.2].
    - facade/ignition 1.8.2 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 44
    - Installation request for facade/ignition-contracts 1.0.0 -> satisfiable by facade/ignition-contracts[1.0.0].
    - facade/ignition-contracts 1.0.0 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 45
    - Installation request for myclabs/deep-copy 1.9.3 -> satisfiable by myclabs/deep-copy[1.9.3].
    - myclabs/deep-copy 1.9.3 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 46
    - Installation request for nunomaduro/collision v3.0.1 -> satisfiable by nunomaduro/collision[v3.0.1].
    - nunomaduro/collision v3.0.1 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 47
    - Installation request for phpdocumentor/reflection-common 2.0.0 -> satisfiable by phpdocumentor/reflection-common[2.0.0].
    - phpdocumentor/reflection-common 2.0.0 requires php >=7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 48
    - Installation request for phpdocumentor/reflection-docblock 4.3.2 -> satisfiable by phpdocumentor/reflection-docblock[4.3.2].
    - phpdocumentor/reflection-docblock 4.3.2 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 49
    - Installation request for phpdocumentor/type-resolver 1.0.1 -> satisfiable by phpdocumentor/type-resolver[1.0.1].
    - phpdocumentor/type-resolver 1.0.1 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 50
    - Installation request for phpunit/php-code-coverage 7.0.8 -> satisfiable by phpunit/php-code-coverage[7.0.8].
    - phpunit/php-code-coverage 7.0.8 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 51
    - Installation request for phpunit/php-file-iterator 2.0.2 -> satisfiable by phpunit/php-file-iterator[2.0.2].
    - phpunit/php-file-iterator 2.0.2 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 52
    - Installation request for phpunit/php-timer 2.1.2 -> satisfiable by phpunit/php-timer[2.1.2].
    - phpunit/php-timer 2.1.2 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 53
    - Installation request for phpunit/php-token-stream 3.1.1 -> satisfiable by phpunit/php-token-stream[3.1.1].
    - phpunit/php-token-stream 3.1.1 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 54
    - Installation request for phpunit/phpunit 8.3.5 -> satisfiable by phpunit/phpunit[8.3.5].
    - phpunit/phpunit 8.3.5 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 55
    - Installation request for sebastian/comparator 3.0.2 -> satisfiable by sebastian/comparator[3.0.2].
    - sebastian/comparator 3.0.2 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 56
    - Installation request for sebastian/diff 3.0.2 -> satisfiable by sebastian/diff[3.0.2].
    - sebastian/diff 3.0.2 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 57
    - Installation request for sebastian/environment 4.2.2 -> satisfiable by sebastian/environment[4.2.2].
    - sebastian/environment 4.2.2 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 58
    - Installation request for sebastian/exporter 3.1.2 -> satisfiable by sebastian/exporter[3.1.2].
    - sebastian/exporter 3.1.2 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 59
    - Installation request for sebastian/global-state 3.0.0 -> satisfiable by sebastian/global-state[3.0.0].
    - sebastian/global-state 3.0.0 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 60
    - Installation request for sebastian/object-enumerator 3.0.3 -> satisfiable by sebastian/object-enumerator[3.0.3].
    - sebastian/object-enumerator 3.0.3 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 61
    - Installation request for sebastian/object-reflector 1.1.1 -> satisfiable by sebastian/object-reflector[1.1.1].
    - sebastian/object-reflector 1.1.1 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 62
    - Installation request for sebastian/recursion-context 3.0.0 -> satisfiable by sebastian/recursion-context[3.0.0].
    - sebastian/recursion-context 3.0.0 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 63
    - Installation request for sebastian/resource-operations 2.0.1 -> satisfiable by sebastian/resource-operations[2.0.1].
    - sebastian/resource-operations 2.0.1 requires php ^7.1 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 64
    - Installation request for sebastian/type 1.1.3 -> satisfiable by sebastian/type[1.1.3].
    - sebastian/type 1.1.3 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 65
    - Installation request for theseer/tokenizer 1.1.3 -> satisfiable by theseer/tokenizer[1.1.3].
    - theseer/tokenizer 1.1.3 requires php ^7.0 -> your PHP version (5.6.40) does not satisfy that requirement.
  Problem 66
    - paragonie/random_compat v9.99.99 requires php ^7 -> your PHP version (5.6.40) does not satisfy that requirement.
    - ramsey/uuid 3.8.0 requires paragonie/random_compat ^1.0|^2.0|9.99.99 -> satisfiable by paragonie/random_compat[v9.99.99].
    - Installation request for ramsey/uuid 3.8.0 -> satisfiable by ramsey/uuid[3.8.0].

**Comment by PovilasKorop** [comment]
@mafuz well the error is clear. You need PHP 7.2 version, and yours is 5.6. Please upgrade.

**Comment by mafuz** [comment]
I upgraded even php 7.3.1 but am still getting the same error this is my version on dashboard PHP Version 7.3.11

**Comment by PovilasKorop** [comment]
@mafuz you added but probably didn't configure it for both FPM and CLI or launching from wrong folder.

**Comment by mafuz** [comment]
I just install xampp yesterday and the php version on it was 7.2 so everything is new,, and if should follow your recommendation where do I find  both the FPM and the CLI. Thank you

**Comment by PovilasKorop** [comment]
@mafuz well error says it clearly: `your PHP version (5.6.40)` - so the error is totally not in our code, it's somewhere in your configuration.

**Comment by mafuz** [comment]
Please Sir could you kindly direct me how to configure it properly if am not doing it right

**Comment by PovilasKorop** [comment]
@mafuz we don't provide free support for PHP configuration, sorry

**Comment by mafuz** [comment]
Thank you Godbless
