### ISSUE TITLE
Buy Ticket - The POST method is not supported for this route. Supported methods: GET, HEAD. 

### ISSUE THREAD

**Issue by Urbannet** [LaravelDaily/Laravel-Event-Conference-Demo#6]
Hello
When I try to buy a ticket i have this error:
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The POST method is not supported for this route. Supported methods: GET, HEAD. 
Your help please.
I am in local

**Comment by PovilasKorop** [comment]
@Urbannet we didn't implement Buy Ticket feature in this repository.
