### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by Saifkhan-rkp** [LaravelDaily/Laravel-Event-Conference-Demo#7]
php artisan migrate -seed

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [1049] Unknown database 'laravel' (SQL: select * from information_schema.tables where table_schema = laravel and table_name = migrations and table_type = 'BASE TABLE')

  at C:\User\abc\Desktop\larvel_Backend\Laravel-Event-Conference-Demo\vendor\laravel\framework\src\Illuminate\Database\Connection.php:671
    667▕         // If an exception occurs when attempting to run a query, we'll format the error
    668▕         // message to include the bindings with SQL, which will make this exception a
    669▕         // lot more helpful to the developer instead of just the database's errors.
    670▕         catch (Exception $e) {
  ➜ 671▕             throw new QueryException(
    672▕                 $query, $this->prepareBindings($bindings), $e
    673▕             );
    674▕         }
    675▕

  • Database name seems incorrect: You're using the default database name `laravel`. This database does not exist.

    Edit the `.env` file and use the correct database name in the `DB_DATABASE` key.
    https://laravel.com/docs/master/database#configuration

**Comment by PovilasKorop** [comment]
@sssplCodeStar the error is clear: check database credentials in env file and if database exists

**Comment by Saifkhan-rkp** [comment]
get it...!
and thanks a lot such a great project..
